### ISSUE TITLE
[Meta] Restructure the TOC to make it easier for users to find content

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#1036]
As we grow our content, we need to have the right structure in place. This issue documents the planned updates to the TOC in the current structure. Further improvements will be made once we move to a new site design.     

Here is a draft of the proposed updated navigation:  
- [x] Getting Started with OpenSearch 
Introduction to OpenSearch
Version History
Breaking Changes

- [x] Installation and Configuration 
Installing OpenSearch (Tarball, Docker, Helm, RPM, Ansible Playbook)
Installing OpenSearch Plugins
Migrating/Upgrading to OpenSearch
Configuring OpenSearch
Installing and Configuring OpenSearch Dashboards (Tarball, Docker, Helm, RPM) 
Installing Dashboards Plugins
   

- [ ] OpenSearch Dashboards
Get Started
Discover
Dashboard
Visualize
Report and Share
Alert and Detect
Management

- [ ] Security (About Security) 
Configuring Security
Authentication
Access Control
Auditing

- [ ] Index and Ingestion 
Index Templates
Units and Data Types
Indexing APIs
Reindexing
Index Aliases
Data Streams
Index Management
Ingestion Nodes
Segment Replication
Field Types

- [ ] Observability 
Event Analytics
Operational Panels
Piped Processing Language
Notebooks
Trace Analytics
Log Analytics
Security Analytics
Anomaly Detection Synthetics

- [ ] Search and Query
Search Query Types
Query DSL: Fuzzy Query
Search Templates
Autocomplete
Paginate Results
Scroll
Sort
Highlight Matches
Asynchronous Search
Cross Cluster Search
Machine Learning
KNN
Aggregations
Indexing back pressure
SQL
Cluster settings
Learn to Rank

- [ ] Availability and Recovery 
Snapshots
Cluster Replication
Get Started
Auto-follow
Permissions
Settings
Cross-cluster replication API

- [ ] Manage, Monitor, and Tune 
Stack Management
Performance Analyzer 
From OpenDistro
Alerting
Notifications
Anomaly Detection

- [ ] Machine Learning
ML Lifecylcle
ML Commons API
Supported Algorithms

- [x] Clients 
Python client
.NET clients
Ruby client
Perl client
Rust client
JavaScript client
Java High-Level REST client
Java client
PHP client
Go client

- [x] Tools 
OpenSearch CLI
Data Prepper
Agents and Ingestion Tools
Grafana
Logstash

- [x] OpenSource API Reference
REST APIs
Common REST parameters
Popular APIs

- [ ] Troubleshooting

- [ ] Developer Guides (links to Javadocs, Dashboards, OpenSearch, Security)

**Comment by hdhalter** [comment]
Target completion = October 31

**Comment by Naarcha-AWS** [comment]
Added Due Dates to each line item, with an eye to categorizing each based on like sections.

**Comment by Naarcha-AWS** [comment]
Here's a linear view of estimated section completion dates:

#### 10/14/2022

- API Reference

#### 10/19/2022 

- Clients
- Tools

#### 10/21/2022

- Index and Ingestion
- Availability and Recovery 

#### 10/26/2002

- Getting Started
- Installation and Configuration

#### 10/28/2022

- Security

#### 11/2/2022

- Observability

#### 11/4/2022

- Search and Query

#### 11/16/2022

- Dashboards

**Comment by Naarcha-AWS** [comment]
Based on the work for the API reference section, I'm adjusting the dates for each section to leave additional room between sections and to allow additional time to complete the task.

New ETA: 11/23/2022

**Comment by hdhalter** [comment]
Here is the updated PR for the installation and configuration section: https://github.com/opensearch-project/documentation-website/pull/2130

**Comment by Naarcha-AWS** [comment]
Completed by https://github.com/opensearch-project/documentation-website/pull/2946
