### ISSUE TITLE
[DOC-META] Migrate Data Prepper documentation

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#1267]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.

Migrate any documentation contained in this folder: https://github.com/opensearch-project/data-prepper/tree/main/docs to the documentation-website repository. 

- [x] Overview | https://github.com/opensearch-project/documentation-website/pull/1453
- [x] #1267
- [x] #1485
- [x] #1487 
- [x] #1932 
- [x] #2373 (Replaces #1936) 
- [x] #1941
- [x] #1942
- [x] #1944
- [x] #2018  (Replaces #1931 )
- [x] #1977  (Replaces #1888) 
- [x] #1873  
- [x] #1946
- [x] #1947
- [x] #1542 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by dlvenable** [comment]
Expanding on the suggestions in #1542, I'd also like to suggest that we break up the existing page named "Pipelines" to include information to have sub-pages from the list in the description above.

```
Clients and tools
  Data Prepper
    Get Started
    Pipelines
      Trace Analytics
      Log Analytics
      S3 Source
      Simple Pipelines
    Reference
       ...
```

**Comment by dlvenable** [comment]
I believe the following items from the list above are geared more toward developers and should only be in the data-prepper GitHub repository:

* Simulation Development

I also suggest adding the following to opensearch.org because they are for end-users.:

* Expression Syntax
* Monitoring

**Comment by carolxob** [comment]
@hdhalter @Naarcha-AWS Here is the current Table of Contents, which will need to be updated:

1. Overview (index.md)
2. Configure Logstash for Data Prepper
3. Get Started
4. Migrate Open Distro
5. Pipelines
6. Migrate Open Distro
7. Logstash Migration Guide
8. Core APIs
9. Peer Forwarder
10. Simple Pipelines
11. Simulation Development
12. Trace Tuning
13. Logs
14. Monitoring
15. Log Analytics
16. Trace Analytics
17. Error Handling
18. Expression Syntax
19. Configuration Guide (see below)


The Configuration guide (2073) has been broken out into the following structure:
- Configuration Guide (data-prepper-configuration.md)
- - Buffers
- - - Overview
- - - Bounded Blocking
- - Processors
- - - Add Entries
- - - Aggregate
- - - Copy Values
- - - CSV
- - - Date
- - - Delete Entries
- - - Drop Events
- - - Grok
- - - JSON
- - - Key Value
- - - Lowercase String
- - - otel Trace Raw
- - - Processors
- - - Rename Keys
- - - Routes
- - - Service Map Stateful
- - - Sinks
- - - Split String
- - - String Converter
- - - Substitute String
- - - Trim String
- - - Uppercase String
- - Sinks
- - - File
- - - Opensearch
- - - Pipeline
- - - Sinks
- - - stdout
- - Sources
- - - http-source
- - - otel metrics source
- - - s3
- - - sources
