### ISSUE TITLE
[DOC-META] Text analysis content needed

### ISSUE THREAD

**Issue by alicejw1** [opensearch-project/documentation-website#1483]
This meta issue indicates the new pages we need for each of the text analyzers we are currently missing. 
Note: Language analyzer is documented, and the concepts page: [Optimizing text for searches with text analyzers](https://opensearch.org/docs/latest/opensearch/query-dsl/text-analyzers/)

Analyzers (10)
- [ ] Standard analyzer
- [ ] Simple
- [ ] Whitespace
- [ ] Stop
- [ ] Keyword
- [ ] Pattern
- [ ] Fingerprint
- [ ] Custom
- [ ] Stemming
- [ ] Token graphs
 
Language analyzers (24)
- [ ] A page for each language - 24 total. See [Language analyzer](https://opensearch.org/docs/latest/opensearch/query-dsl/text-analyzers/#language-analyzer) section currently on concepts page.  

Tokenizers (14 + index page)
- [ ] Index page
- [ ] Character group
- [ ] Classic
- [ ] Edge n-gram
- [ ] Keyword
- [ ] Letter
- [ ] Lowercase
- [ ] N-gram
- [ ] Path hierarchy
- [ ] Pattern
- [ ] Simple pattern
- [ ] Simple pattern split
- [ ] Standard
- [ ] Thai
- [ ] UAX URL email
- [ ] Whitespace

Token filters (48)
- [ ] Page for each one

Character filters (3 + index page)
- [ ] index page
- [ ] HTML strip
- [ ] Mapping
- [ ] Pattern replace

Normalizers
- [ ] Normalizers

**Comment by alicejw-aws** [comment]
hi @kolchfa-aws , Heather asked me to reassign this ticket to you. Thanks

**Comment by hdhalter** [comment]
Missing: Stemming, token graphs, language analyzers for each language, configuring built-in analyzers, custom analyzers, built-in analyzer reference (8 pages), tokenizers, tokenizer reference (15 pages), token filter reference (48 pages), character filter reference (3 pages), normalizers

**Comment by leanneeliatra** [comment]
I'm starting 'Standard analyzer'. cc @hdhalter

**Comment by leanneeliatra** [comment]
I'm going to work on 
1. Normalizers
2. Character filters (3 + index page)
