### ISSUE TITLE
[DOC] Create use-case specific pages for Data Prepper documentation

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/documentation-website#1846]
**What do you want to do?**
 
- [x] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
The Data Prepper documentation includes four [example pipelines](https://opensearch.org/docs/latest/data-prepper/pipelines/#examples) which relate to specific use-cases.

* [Log ingestion pipeline](https://opensearch.org/docs/latest/data-prepper/pipelines/#log-ingestion-pipeline)
* [Trace analytics pipeline](https://opensearch.org/docs/latest/data-prepper/pipelines/#trace-analytics-pipeline)
* [Metrics pipeline](https://opensearch.org/docs/latest/data-prepper/pipelines/#metrics-pipeline)
* [S3 log ingestion](https://opensearch.org/docs/latest/data-prepper/pipelines/#s3-log-ingestion-pipeline)

The Data Prepper repository includes log ingestion and trace analytics pages which include additional detail such as architecture.

* [Log analytics](https://github.com/opensearch-project/data-prepper/blob/main/docs/log_analytics.md)
* [Trace analytics](https://github.com/opensearch-project/data-prepper/blob/main/docs/trace_analytics.md)

I propose that the OpenSearch.org documentation include three pages with the pipelines mentioned above.

*Trace analytics* - Base this page on the [Trace analytics](https://github.com/opensearch-project/data-prepper/blob/main/docs/trace_analytics.md) page in the data-prepper repository

*Log ingestion* - Base this page on the [Log analytics](https://github.com/opensearch-project/data-prepper/blob/main/docs/log_analytics.md) page in the data-prepper repository.

*S3 log ingestion* - Include the sample S3 pipeline. It could also be good to elaborate some on the architecture here, similar to what the Log analytics page.

*Metrics ingestion* - Include the sample metrics pipeline. It should also have some architectural information to guide pipeline authors and architects.

The overall structure would look like the following:

```
Clients and tools
  Data Prepper
    Get Started
    Pipelines
    Use-cases
      Trace analytics
      Log ingestion
      S3 log ingestion
      Metrics ingestion
    Reference
      ...
```

An alternative structure could be to put the "S3 log ingestion" page below "Log ingestion."

```
Clients and tools
  Data Prepper
    Get Started
    Pipelines
    Use-cases
      Trace analytics
      Log ingestion
        S3 log ingestion
      Metrics ingestion
    Reference
      ...
```

**Tasks**

- [ ] Merge Trace Analytics pipelines page with example pipeline in a new page
- [ ] Merge Log ingestion pipeline page with example pipeline in a new page
- [ ] Create a new page for S3 log ingestion pipeline using the existing example
- [ ] Add architectural information for the S3 log ingestion pipelines
- [ ] Create a new page for metrics ingestion pipeline using the existing example
- [ ] Add architectural information for metrics pipelines

**Comment by cmanning09** [comment]
I like the alternative approach. Enumerating just on the high level use case and then show casing different options to support those use cases in child pages.

**Comment by carolxob** [comment]
@dlvenable I prefer the first suggestion for information architecture reasons - it looks cleaner and more user-friendly.
