### ISSUE TITLE
[META][DOC] Feature Anywhere Documentation

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/documentation-website#2075]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
We have this upcoming feature from Alerting and AD plugins where we want to document this feature on launch.
This feature will let users create/manage/view Alerting monitors/alerts and AD detectors/anomalies on the Dashboard page from the visualizations (currently only supporting line graphs) shown there.
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1798
https://github.com/opensearch-project/alerting/issues/414
https://github.com/opensearch-project/anomaly-detection/issues/521

**Comment by Naarcha-AWS** [comment]
@lezzago: How related is this to https://github.com/opensearch-project/documentation-website/issues/796? Has the name of the feature changed?

**Comment by Naarcha-AWS** [comment]
Reassigning to @alicejw-aws, since she's the active writer for Alerts anywhere.

**Comment by vagimeli** [comment]
Status: Finalizing release date; won't be part of 2.6; writer held doc kickoff meeting 2/13; writer continuing to work with UX and eng and attend feature briefs

**Comment by hdhalter** [comment]
Added 2.9 label.
