### ISSUE TITLE
[DOC-META] Create new Query DSL topic pages 

### ISSUE THREAD

**Issue by alicejw1** [opensearch-project/documentation-website#2173]
Write new [Query DSL](https://opensearch.org/docs/latest/opensearch/query-dsl/index/) topic pages that were identified as missing from the current documentation set: 

**New pages needed**

Each of the following topics require a new page with sub-sections:
- [x] #3068
relevance score, query context (how well doc matches a query clause), filter context (does doc match clause or not), 
- [x] Compound queries
boost, constant score, disjunction max, function score, (add existing [Boolean queries](https://opensearch.org/docs/latest/opensearch/query-dsl/bool/) to this topic)
- [ ] Span queries
containing, field masking, first, multi-term, near, not, or, term, within
- [ ] Geographic queries
bounding box, distance, grid, polygon, geoshape
- [ ] Regular expression queries
all regex expressions available
- [ ] Joining queries
nested, has child, has parent, parent ID
- [ ] Specialized queries
Distance feature, more like this, percolate, rank feature, script, script score, wrapper
- [ ] Parameter queries
minimum should match, rewrite
- [ ] Shape queries
geo-shape query, pre-indexed shape, ignore unmapped, spacial relations (intersect, disjoin, within, contains)

**New subsections needed (existing topic pages)**

The following existing topic pages require new content for the following subsections: 
- [x] [Term-level queries](https://opensearch.org/docs/latest/opensearch/query-dsl/term/)
Fuzzy queries, terms set
- [x] [Full-text queries](https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/)
intervals, combined fields

**Comment by alicejw-aws** [comment]
Hi @macrakis, could you please take a look at the list of main topics (pages) and subsections and let us know if we missed any? Thanks

**Comment by alicejw-aws** [comment]
Hi @macohen, could you please take a look at the list of topics and let me know which are the top three that you think customers need the most? 
I will start writing those first. Thanks

**Comment by hdhalter** [comment]
Reassigning to @kolchfa-aws to take over. Thanks, Fanit!

**Comment by hdhalter** [comment]
Customer feedback suggests that we need to address the query DSL pages. Some are liked higher than others, so this shows the breakdown to date, in order to see where we can prioritize.
- query-dsl/index - 25% likes
- query-dls/full-text - 60% likes
- query-dsl/term - 63% likes
- query-dsl/test-analyizers - 50% likes

Query DSL pages are consistently ranked the highest pages visited week over week.
