### ISSUE TITLE
[META] Create documentation for OpenSearch Benchmark 

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/documentation-website#2862]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 We currently have limited documentation for [OpenSearch Benchmark](https://github.com/opensearch-project/opensearch-benchmark) and the current documentation are more of a developer guide documentation rather than user guides.

We need to create a comprehensive user guides and improve existing developer guide to improve the usability experience of this product.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
NA

=========== Tech writer notes below this line ===========

- [ ] Review existing documentation (in progress)
- [ ] Test in local environment
- [ ] Plan documentation layout
- [ ] TBD

**Comment by bbarani** [comment]
## Acceptance criteria
* The initial version of the documentation cannot be a one pager but should atleast cover
  *   Brief overview 
  *   What and how this tool should be used 
  *   Installation instructions 
  *   Short quick start guide
   *  Sample use cases with recommended workloads
* The readme.md file should be updated on the GitHub repo as well listing basic information (Ex: running against local vs remote cluster)
* Document hardware / Software requirements
* List installation methods along with instructions - Only installation method is PyPi (and local builds)
* List operating system recommendations
    * Ubuntu vs AL2 ( add OS recommendations as part of documentation)
* Frequently Asked questions (FAQ)
* Migration guide ( Rally to OSB? and OSB one version to another)
    * Version matrix ( OpenSearch / ES / Kibana / OpenSearch Dashboards)
* Glossary
* Developing OSB - One page developer setup guide (not a detailed developer guide)

**Comment by bbarani** [comment]
@Naarcha-AWS Any update on the documentation for OSB?

**Comment by hdhalter** [comment]
Jeff is going to switch gears and support you on this, @bbarani.

**Comment by JeffH-AWS** [comment]
Familiarizing myself with the application now.

**Comment by JeffH-AWS** [comment]
The existing docs leave a lot to be desired. Rather than inventing this from the ground up I've made a request for an engineering resource in Slack:

```
Hello team! I'm looking to schedule a 1 hour session to review set up and usage of the [OpenSearch Benchmark utility](https://github.com/opensearch-project/opensearch-benchmark). I'll need this session in order to familiarize myself with the product and get clarification on the steps outlined in the existing README.md file. It looks like https://w.amazon.com/bin/view/OpenSearch_Project/Teams/Engineering_Effectiveness/OfficeHours/ isn't getting updated, and I will need more than 15 minutes anyway. 
[@bbarani](https://amzn-aws.slack.com/team/W016U2EAM7Y)
 can you help me identify a resource so I can work on scheduling a session for the next few days or next week?
```

**Comment by JeffH-AWS** [comment]
Meeting scheduled for Monday 3/20 @ 1pm PST w/ some of the engineers that work on OSB.

**Comment by JeffH-AWS** [comment]
@bbarani I'm meeting with engineers who are going to demo the functionality today. Regarding the acceptance criteria, there are a few items listed that need to be addressed with the OSB team rather than with the documentation team.

Specifically:

- The readme.md file should be updated on the GitHub repo as well listing basic information (Ex: running against local vs remote cluster)
- Developing OSB - One page developer setup guide (not a detailed developer guide)

The README.md is owned by the OSB repo, and developer guides have not been included in the documentation website thus far, so I'm wondering where that requirement is coming from.

Additionally, I will need a SME to provide the following:

- Sample use cases with recommended workloads
- Document hardware / Software requirements
- List operating system recommendations
- FAQ
- Migration guide with instructions for how to move from Rally to OSB
- Glossary

In the meantime I can begin writing the overview, but all of those 6 items will need to be furnished by a developer, and then I can take it and make it look nice on the site.

**Comment by JeffH-AWS** [comment]
Since it looks like over half of the acceptance criteria can't be delivered without additional engineering resources I'm tagging this issue as blocked.

**Comment by JeffH-AWS** [comment]
This is going to be challenging to document because there isn't existing documentation for usage.

I'm currently looking at a TLS cert error:

```
[ERROR] Cannot execute_test. Error in test execution orchestrator (ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)))
```

This is preventing any test from executing.

**Comment by JeffH-AWS** [comment]
After digging through the code base myself I was able to identify an undocumented client option called `verify_certs` that must be set to `false` for self-signed certificates. I'm hoping that there's a way to pass a root cert for untrusted CAs so that the connection can be established without just turning off encryption.

**Comment by bbarani** [comment]
>The initial version of the documentation cannot be a one pager but should atleast cover
>- Brief overview
>- What and how this tool should be used
>- Installation instructions
>- Short quick start guide
>- Sample use cases with recommended workloads


@opensearch-project/benchmark-core can you please help @JeffH-AWS with the topics to cover under the each section listed above along with any frequently asked questions that he can add to FAQ section?

**Comment by JeffH-AWS** [comment]
Continuing work on branch 2862-opensearch-benchmark-section

**Comment by JeffH-AWS** [comment]
I'll be ready to open a new draft PR shortly. It will include:

- Overview
- Getting Started
- Installing OpenSearch Benchmark
- Configuring OpenSearch Benchmark (basic details)

**Comment by Naarcha-AWS** [comment]
Taking this one over

**Comment by bbarani** [comment]
We have released first version of OpenSearch benchmark [documentation](https://opensearch.org/docs/latest/benchmark/index/)
