### ISSUE TITLE
[DISCUSS] Adding better meta-information to docs pages

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/documentation-website#3528]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 When looking over the documentation website I have a hard time determining what is what. Am I looking at a plugin for OpenSearch or OpenSearch Dashbaords or is this documentation for a general topic? How do I know if this plugin is already installed? 
 
 I'm curious if this experience is unique to me or if others are having the same challenges. Also, if so is there a way we can resolve this? Maybe tags at the top of the page or a sidebar item with information on what it is, where to find it on GitHub, and how to install it.

**Comment by Naarcha-AWS** [comment]
@dtaivpp: Could you provide a more specific example? Keep in mind that we recently updated the TOC to be less plugin-centric and more use-case centric, in keeping with the project's direction away from plugins (see https://github.com/opensearch-project/OpenSearch/issues/2447). 

Furthermore, there is discussion about spinning off the following documentation into their own individual sections away from OpenSearch core functionality, including their own versioning:

- Data Prepper
- Dashboards
- Clients

**Comment by dtaivpp** [comment]
It is okay to focus on use-cases more than the individual components however the components (whether extensions or plugins) need to be present. Take [security-analytics](https://opensearch.org/docs/latest/security-analytics/index/) for example. You need to read a fair bit into the page to discover that is is available as a plugin for dashboards.

Organizations doing a "best practice" deployment they would only be deploying with exactly the plugins they need. If they came and found security analytics they would need to do the digging to find it's available as a plugin for OpenSearch dashboards and is [installed in a similar manner to other plugins](https://opensearch.org/docs/1.2/dashboards/install/plugins/#install). 

It can be frustrating going to the setup page and not seeing how to deploy/enable that particular plugin.

**Comment by dtaivpp** [comment]
Okay probably should have avoided using the word meta because its a little overloaded in this context. Yeah I was just thinking something like a call out on the side of the page to give the additional information like below. The text could link to installing plugins for OpenSearch/OpenSearch Dashboards. 

<img width="1635" alt="Screenshot 2023-03-23 at 9 49 14 AM" src="https://user-images.githubusercontent.com/17506770/227224281-b87650db-4a71-4cae-9829-6f908f51931b.png">

Agreed though it may be helpful to just have a section for each even if its just a one liner to describe how that plugin /extension is installed.

**Comment by natebower** [comment]
Closing as stale
