### ISSUE TITLE
[DOC] Missing api documentation

### ISSUE THREAD

**Issue by curq** [opensearch-project/documentation-website#3614]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [X] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 In the issue [https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3714](url) I was asked to update links in Dev Tools console in Opensearch-Dashboards repo. I was asked to list all the missing docs. First I audited documentation values in JSON files in https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/console/server/lib/spec_definitions/json/generated. I found several missing docs, I will list respective filenames:
- cat.master
- cluster.delete_voting_config_exclusions
- cluster.pending_tasks
- cluster.post_voting_config_exclusions
- cluster.state
- cluster.reroute
- field_caps
- indices.add_block
- indices.flush_synced
- indices.flush
- indices.forcemerge
- indices.get_upgrade
- indices.recovery
- indices.refresh
- indices.resolve_index
- indices.rollover
- indices.segments
- indices.shard_stores
- indices.simulate_index
- indices.simulate_template
- indices.stats - https://github.com/opensearch-project/documentation-website/pull/4892
- indices.upgrade
- indices.validate_query
- ingest.processor_grok
- mtermvectors
- remote_store.restore
- search_shards
- snapshot.cleanup_repository
- snapshot.clone
- termvectors

Another important notes is that only PUT _component_template is documented while DELETE, HEAD and GET are not.
Additionally, in reindex, delete by query and update by query rethrottle variations are not documented (reindex_rethrottle, delete_by_query_rethrottle, update_by_query_rethrottle).

Lastly after checking https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/console/server/lib/spec_definitions/js/ingest.ts it seems like a lot of processors are not documented. The list:
- append-processor
- bytes-processor
- ingest-circle-processor
- convert-processor
- date-index-name-processor
- dissect-processor
- dot-expand-processor
- drop-processor 
- fail-processor
- foreach-processor
- geoip-processor
- gsub-processor
- htmlstrip-processor
- inference-processor
- join-processor
- kv-processor  
- pipeline-processor
- remove-processor
- rename-processor 
- script-processor
- set-processor
- ingest-node-set-security-user-processor
- sort-processor
- urldecode-processor
- user-agent-processor

Please tell me if missed something and they are actually documented. Also, please comment if you need additional any additional info.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/documentation-website/issues/url

**Comment by hdhalter** [comment]
Thanks for entering this issue, Sirazh! We have a number of APIs in our backlog to document: https://github.com/opensearch-project/documentation-website/issues?q=is%3Aissue+is%3Aopen+label%3AAPI, so we can cross-check against your list.

**Comment by hdhalter** [comment]
Assigning to @ariamarble , since she is assigned to the other APIs, and @kolchfa-aws for visibility.

**Comment by hdhalter** [comment]
Hi @curq - The missing processors are being addressed according to this issue: https://github.com/opensearch-project/documentation-website/issues/4193

Removed @ariamarble and added @vagimeli.

**Comment by hdhalter** [comment]
I did a check to see if we had issues for the undocumented APIs. Most of them do, but I commented if it doesn't.
- [ ] cat.master - no issue exists
- [ ] cluster.delete_voting_config_exclusions https://github.com/opensearch-project/documentation-website/issues/2092
- [ ] cluster.pending_tasks https://github.com/opensearch-project/documentation-website/issues/2092
- [ ] cluster.post_voting_config_exclusions https://github.com/opensearch-project/documentation-website/issues/2092
- [ ] cluster.state https://github.com/opensearch-project/documentation-website/issues/2092
- [ ] cluster.reroute https://github.com/opensearch-project/documentation-website/issues/2092
- [ ] field_caps - no issue exists
- [ ] indices.add_block - no issue exists
- [ ] indices.flush_synced - https://github.com/opensearch-project/documentation-website/issues/2096
- [ ] indices.flush-  https://github.com/opensearch-project/documentation-website/issues/2096
- [ ] indices.forcemerge -https://github.com/opensearch-project/documentation-website/issues/2097
- [ ] indices.get_upgrade - no issue exists
- [ ] indices.recovery -https://github.com/opensearch-project/documentation-website/issues/2098
- [ ] indices.refresh - https://github.com/opensearch-project/documentation-website/issues/2099
- [ ] indices.resolve_index - https://github.com/opensearch-project/documentation-website/issues/2114
- [ ] indices.rollover  https://github.com/opensearch-project/documentation-website/issues/2100
- [ ] indices.segments - https://github.com/opensearch-project/documentation-website/issues/2101
- [ ] indices.shard_stores - https://github.com/opensearch-project/documentation-website/issues/2102
- [ ] indices.simulate_index - https://github.com/opensearch-project/documentation-website/issues/2115
- [ ] indices.simulate_template - https://github.com/opensearch-project/documentation-website/issues/2115
- [ ] indices.stats - https://github.com/opensearch-project/documentation-website/issues/2103
- [ ] indices.upgrade - no issue exists
- [ ] indices.validate_query -https://github.com/opensearch-project/documentation-website/issues/2104
- [ ] ingest.processor_grok - https://github.com/opensearch-project/documentation-website/issues/2105
- [ ] mtermvectors - https://github.com/opensearch-project/documentation-website/issues/2108
- [ ]  remote_store.restore - no issue exists
- [ ] search_shards - https://github.com/opensearch-project/documentation-website/issues/2110
- [ ] snapshot.cleanup_repository - https://github.com/opensearch-project/documentation-website/issues/2111
- [ ] snapshot.clone - https://github.com/opensearch-project/documentation-website/issues/2111
- [ ] termvectors -https://github.com/opensearch-project/documentation-website/issues/2108

**Comment by hdhalter** [comment]
We also have issues for these that are not in the above list:
- [ ] DELETE /_component_template/<name> - https://github.com/opensearch-project/documentation-website/issues/2113
- [ ] HEAD /_component_template/<name> https://github.com/opensearch-project/documentation-website/issues/2113
- [ ] GET /_component_template/<name> https://github.com/opensearch-project/documentation-website/issues/2113
- [ ] POST /_component_template/<name> (already have PUT)https://github.com/opensearch-project/documentation-website/issues/2113 
- [ ] POST /_delete_by_query/<task_id>/_rethrottle -https://github.com/opensearch-project/documentation-website/issues/2112
- [ ] POST /_update_by_query/<task_id>/_rethrottle https://github.com/opensearch-project/documentation-website/issues/2112
- [ ] POST /_reindex/<task_id>/_rethrottle https://github.com/opensearch-project/documentation-website/issues/2112

**Comment by kolchfa-aws** [comment]
> I did a check to see if we had issues for the undocumented APIs. Most of them do, but I commented if it doesn't.
> 
>     * [ ]  cat.master - no issue exists This is documented https://opensearch.org/docs/latest/api-reference/cat/cat-cluster_manager/
> 
>     * [ ]  cluster.delete_voting_config_exclusions [[DOC]Create documentation for _cluster APIs #2092](https://github.com/opensearch-project/documentation-website/issues/2092)
> 
>     * [ ]  cluster.pending_tasks [[DOC]Create documentation for _cluster APIs #2092](https://github.com/opensearch-project/documentation-website/issues/2092)
> 
>     * [ ]  cluster.post_voting_config_exclusions [[DOC]Create documentation for _cluster APIs #2092](https://github.com/opensearch-project/documentation-website/issues/2092)
> 
>     * [ ]  cluster.state [[DOC]Create documentation for _cluster APIs #2092](https://github.com/opensearch-project/documentation-website/issues/2092)
> 
>     * [ ]  cluster.reroute [[DOC]Create documentation for _cluster APIs #2092](https://github.com/opensearch-project/documentation-website/issues/2092)
> 
>     * [ ]  field_caps - no issue exists The issue is #2094
> 
>     * [ ]  indices.add_block - no issue exists
> 
>     * [ ]  indices.flush_synced - [[DOC]Create documentation for _flush APIs #2096](https://github.com/opensearch-project/documentation-website/issues/2096)
> 
>     * [ ]  indices.flush-  [[DOC]Create documentation for _flush APIs #2096](https://github.com/opensearch-project/documentation-website/issues/2096)
> 
>     * [ ]  indices.forcemerge -[[DOC]Create documentation for _forcemerge API #2097](https://github.com/opensearch-project/documentation-website/issues/2097)
> 
>     * [ ]  indices.get_upgrade - no issue exists
> 
>     * [ ]  indices.recovery -[[DOC]Create documentation for _recovery API #2098](https://github.com/opensearch-project/documentation-website/issues/2098)
> 
>     * [ ]  indices.refresh - [[DOC]Create documentation for _refresh API #2099](https://github.com/opensearch-project/documentation-website/issues/2099)
> 
>     * [ ]  indices.resolve_index - [[DOC]Create documentation for _resolve API #2114](https://github.com/opensearch-project/documentation-website/issues/2114)
> 
>     * [ ]  indices.rollover  [[DOC]Create documentation for _rollover API #2100](https://github.com/opensearch-project/documentation-website/issues/2100)
> 
>     * [ ]  indices.segments - [[DOC]Create documentation for _segments API #2101](https://github.com/opensearch-project/documentation-website/issues/2101)
> 
>     * [ ]  indices.shard_stores - [[DOC]Create documentation for _shard_stores API #2102](https://github.com/opensearch-project/documentation-website/issues/2102)
> 
>     * [ ]  indices.simulate_index - [[DOC]Create documentation for _index_template API #2115](https://github.com/opensearch-project/documentation-website/issues/2115)
> 
>     * [ ]  indices.simulate_template - [[DOC]Create documentation for _index_template API #2115](https://github.com/opensearch-project/documentation-website/issues/2115)
> 
>     * [ ]  indices.stats - [[DOC]Create documentation for _stats API #2103](https://github.com/opensearch-project/documentation-website/issues/2103)
> 
>     * [ ]  indices.upgrade - no issue exists
> 
>     * [ ]  indices.validate_query -[[DOC]Create documentation for _validate API #2104](https://github.com/opensearch-project/documentation-website/issues/2104)
> 
>     * [ ]  ingest.processor_grok - [[DOC]Create documentation for GET /_ingest/processor/grok API #2105](https://github.com/opensearch-project/documentation-website/issues/2105)
> 
>     * [ ]  mtermvectors - [[DOC]Create documentation for _mtermvectors API #2108](https://github.com/opensearch-project/documentation-website/issues/2108)
> 
>     * [ ]   remote_store.restore - no issue exists
> 
>     * [ ]  search_shards - [[DOC]Create documentation for _search_shards API #2110](https://github.com/opensearch-project/documentation-website/issues/2110)
> 
>     * [ ]  snapshot.cleanup_repository - [[DOC]Create documentation for _snapshot API #2111](https://github.com/opensearch-project/documentation-website/issues/2111)
> 
>     * [ ]  snapshot.clone - [[DOC]Create documentation for _snapshot API #2111](https://github.com/opensearch-project/documentation-website/issues/2111)
> 
>     * [ ]  termvectors -[[DOC]Create documentation for _mtermvectors API #2108](https://github.com/opensearch-project/documentation-website/issues/2108)

**Comment by vagimeli** [comment]
See PR #4299 for updates on processors documentation

**Comment by hdhalter** [comment]
Let's keep this open until we have all APIs complete.

**Comment by Naarcha-AWS** [comment]
Additional missing APIs uncovered:

- [ ] PUT `data_streams`
- [ ] DELETE `data_streams`
- [ ] GET `data_streams`
- [ ] PUT `data_streams/migrate`
- [ ] GET `data_streams/promote`
- [ ] PUT `data_streams/modify`

**Comment by dblock** [comment]
I propose we invest some hands into https://github.com/opensearch-project/documentation-website/issues/7700 to bridge all the gaps with automation.

**Comment by natebower** [comment]
@AntonEliatra Does this one need to stay open?

**Comment by AntonEliatra** [comment]
@natebower You can assign to me and I will review shortly

**Comment by kolchfa-aws** [comment]
## API Documentation Update

### ✅ **IMPLEMENTED APIs:**

#### **Core Index APIs:**
- `indices.flush` → `_api-reference/index-apis/flush.md`
- `indices.forcemerge` → `_api-reference/index-apis/force-merge.md`
- `indices.recovery` → `_api-reference/index-apis/recover.md`
- `indices.refresh` → `_api-reference/index-apis/refresh.md`
- `indices.rollover` → `_api-reference/index-apis/rollover.md`
- `indices.segments` → `_api-reference/index-apis/segment.md`
- `indices.stats` → `_api-reference/index-apis/stats.md`
- `indices.add_block` → `_api-reference/index-apis/blocks.md`
- `indices.resolve_index` → `_api-reference/index-apis/resolve-index.md`
- `indices.validate_query` → `_api-reference/search-apis/validate.md`
- `indices.simulate_template` → _api-reference/index-apis/simulate-index-template.md
- `indices.simulate_index` → _api-reference/index-apis/simulate-index-template.md

#### **Cluster Management APIs:**
- `cluster.pending_tasks` → `_api-reference/cluster-api/cluster-pending-tasks.md`
- `cluster.state` → `_api-reference/cluster-api/cluster-state.md`
- `cluster.reroute` → `_api-reference/cluster-api/cluster-reroute.md`
- `cluster.delete_voting_config_exclusions` → `_api-reference/cluster-api/cluster-voting-configuration-exclusions.md`
- `cluster.post_voting_config_exclusions` → `_api-reference/cluster-api/cluster-voting-configuration-exclusions.md`

#### **Search & Document APIs:**
- `field_caps` → `_api-reference/search-apis/field-caps.md`
- `search_shards` → `_api-reference/search-apis/search-shards.md`
- `mtermvectors` → `_api-reference/document-apis/mtermvectors.md`
- `termvectors` → `_api-reference/document-apis/termvector.md`

#### **Snapshot APIs:**
- `snapshot.cleanup_repository` → `_api-reference/snapshots/cleanup-snapshot-repository.md`
- `snapshot.clone` → `_api-reference/snapshots/clone-snapshot.md`

#### **CAT APIs:**
- `cat.master` → `_api-reference/cat/cat-cluster_manager.md`

#### **Rethrottle APIs:**
- `reindex_rethrottle` → `_api-reference/tasks/rethrottle.md`
- `delete_by_query_rethrottle` → `_api-reference/tasks/rethrottle.md`
- `update_by_query_rethrottle` → `_api-reference/tasks/rethrottle.md`

#### **Ingest Processors:**
All 25+ processors now documented in `_ingest-pipelines/processors/`:
append, bytes, convert, date-index-name, dissect, dot-expander, drop, fail, foreach, geoip, gsub, html-strip, join, kv, pipeline, remove, rename, script, set, sort, urldecode, user-agent

#### **Component Templates (Partial):**
- `PUT _component_template` - documented
- `GET _component_template` - documented

#### **Remote store:**

- `remote_store.restore` → `_tuning-your-cluster/availability-and-recovery/remote-store/index.md`

### ❌ **NOT YET IMPLEMENTED:**

#### **Component Template Operations:**
- `DELETE _component_template` - PR #11441
- `HEAD _component_template`- PR #11441

#### **Index APIs:**

- `indices.shard_stores` (index-level) - moved to the index directory in #11443 

### **Don't need documenting:**
- `ingest.processor_grok` (processor documented, no specific API exists)
- `indices.upgrade` (deprecated)
- `indices.flush_synced` (deprecated)
- `indices.get_upgrade` (deprecated)
