### ISSUE TITLE
[DOC] Concurrent Segment Search support in OpenSearch

### ISSUE THREAD

**Issue by sohami** [opensearch-project/documentation-website#3662]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Add documentation about the concurrent segment search functionality and the knobs it exposes for the users to consume. For now adding as a placeholder issue and details will be added later.

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
https://github.com/opensearch-project/OpenSearch/issues/2587

** Additional Issues **
https://github.com/opensearch-project/documentation-website/issues/4281

**Comment by Naarcha-AWS** [comment]
@sohami: Which version is concurrent segment search going into?

**Comment by sohami** [comment]
> @sohami: Which version is concurrent segment search going into?

@Naarcha-AWS For now we are targeting for 2.10

**Comment by jed326** [comment]
As a part of https://github.com/opensearch-project/OpenSearch/issues/8371 we are updating the definition of `terminate_after` search parameter to be per leaf slice instead of per shard. In the non-concurrent search case there is no behavior change.

**Comment by jed326** [comment]
As a part of https://github.com/opensearch-project/OpenSearch/pull/9469 there is a new `supportsConcurrentSegmentSearch` method in the `AggregatorFactory` class that needs to be overridden for any new aggregators that intend to support concurrent segment search.

**Comment by kolchfa-aws** [comment]
When this feature is GA, we should incorporate the additional introduced/modified fields in their respective tables in the API pages. See #4990 for the changed APIs.

**Comment by kolchfa-aws** [comment]
@sohami Is there any documentation needed for the 2.11 version for this issue?

**Comment by kolchfa-aws** [comment]
Per offline sync with @sohami, there's no work to be done for 2.11 for this issue

**Comment by sohami** [comment]
Yes we created separate doc issue for 2.11 where specific updates are needed. Thanks for moving this to 2.12 for now.

* https://github.com/opensearch-project/documentation-website/issues/5007
* https://github.com/opensearch-project/documentation-website/issues/5142

**Comment by kolchfa-aws** [comment]
@sohami Is there any documentation needed for the 2.12 version for this issue? Or is all the work done in #4281? Thanks!

**Comment by jed326** [comment]
Taking note to document "slice_size" change from https://github.com/opensearch-project/OpenSearch/pull/11585

**Comment by jed326** [comment]
Taking note to document descending sort considerations wrt concurrent segment search

References:
- https://github.com/opensearch-project/OpenSearch/issues/8167
- https://github.com/apache/lucene/issues/12448
- https://github.com/opensearch-project/OpenSearch/issues/10867#issuecomment-1795813499

**Comment by jed326** [comment]
@kolchfa-aws Compiling a list of all the docs related updates we will need for concurrent segment search GA:
- [x] Profile API changes - https://github.com/opensearch-project/documentation-website/issues/4281
- [ ] Concurrent segment search cluster & Index settings - https://github.com/opensearch-project/documentation-website/issues/3662#issuecomment-1587717103
- [ ] Add new concurrent search stats to main stats page - https://github.com/opensearch-project/documentation-website/pull/4990#discussion_r1321675401
- [ ] Add `slice_size` change to terms aggregation documentation - https://github.com/opensearch-project/documentation-website/issues/3662#issuecomment-1852948261
- [ ] Add descending sort considerations wrt concurrent segment search - https://github.com/opensearch-project/documentation-website/issues/3662#issuecomment-1865079784

@sohami @ticheng-aws @yigithub @neetikasinghal please let me know if you think of anything else!

**Comment by ticheng-aws** [comment]
> @kolchfa-aws Compiling a list of all the docs related updates we will need for concurrent segment search GA:
> 
> * [x]  Profile API changes - [[DOC] Update search profile API documentation with concurrency related changes #4281](https://github.com/opensearch-project/documentation-website/issues/4281)
> * [ ]  Concurrent segment search cluster & Index settings - [[DOC] Concurrent Segment Search support in OpenSearch #3662 (comment)](https://github.com/opensearch-project/documentation-website/issues/3662#issuecomment-1587717103)
> * [ ]  Add new concurrent search stats to main stats page - [Add concurrent segment search documentation #4990 (comment)](https://github.com/opensearch-project/documentation-website/pull/4990#discussion_r1321675401)
> * [ ]  Add `slice_size` change to terms aggregation documentation - [[DOC] Concurrent Segment Search support in OpenSearch #3662 (comment)](https://github.com/opensearch-project/documentation-website/issues/3662#issuecomment-1852948261)
> * [ ]  Add descending sort considerations wrt concurrent segment search - [[DOC] Concurrent Segment Search support in OpenSearch #3662 (comment)](https://github.com/opensearch-project/documentation-website/issues/3662#issuecomment-1865079784)
> 
> @sohami @ticheng-aws @yigithub @neetikasinghal please let me know if you think of anything else!

We also need a PR to remove the "experimental" keyword altogether.

**Comment by jed326** [comment]
Added terms aggregation concurrent search docs and improvements here: https://github.com/opensearch-project/documentation-website/pull/6355

**Comment by jed326** [comment]
Summarizing the concurrent search related PRs we have floating around:
- https://github.com/opensearch-project/documentation-website/pull/6356
- https://github.com/opensearch-project/documentation-website/pull/6355
- https://github.com/opensearch-project/documentation-website/pull/6362
