### ISSUE TITLE
[DOC] Create a guide for using the S3 source, including recommended practices

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/documentation-website#3833]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [x] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 
We want to have a guide available for using the Data Prepper `s3` source.

At the same time we will be creating some common use-case specific documentation (e.g. for AWS ALB or VPC logs).

I'm thinking of having the following structure:

```
Data Prepper
   Common use cases
       S3 logs
          ALB logs
          VPC logs
```

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

## Tasks

- [x] Create general S3 logs documentation
- [ ] Create AWS ALB specific documentation

**Comment by dlvenable** [comment]
I'm planning to work on this, feel free to assign this issue to me.

Also, I'd like some feedback on the proposed document structure.

**Comment by Naarcha-AWS** [comment]
Let's plan to do this in the new repository, unless we receive push back users.
