### ISSUE TITLE
[DOC] META: Restructure TOC Observability, Alerting, Anomaly Detection, and Notifications

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/documentation-website#4167]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Actions items for restructuring TOC

* Move AD under machine learning
* Move alerting and notifications to platform-level documentation, as they aren't only observability related
* Card sort to gather community feedback
* 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by Naarcha-AWS** [comment]
This a duplicate of https://github.com/opensearch-project/documentation-website/issues/3129. I might close the old one in favor of this one.
