### ISSUE TITLE
[DOC] Add missing Core REST API endpoints

### ISSUE THREAD

**Issue by Naarcha-AWS** [opensearch-project/documentation-website#424]
Because the OpenSearch REST API documentation is no longer automated, we need to create a feature complete API reference, one the includes all endpoints, request bodies, and responses. 

For reference on what ideal REST API reference page looks like, see the [OpenSearch Create Index API](https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/create-index/).

## List of missing endpoints

To assist in achieving this goal, I've put together a list of APIs that are missing, based on cross-referencing the old [Open Distro API reference](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/). NOTE: This list is not comprehensive and might not include all missing endpoints.

- [x] [mget](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#mget)
- [x] [nodes.hot_threads](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#nodeshot_threads)
- [x] [nodes.info](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#nodesinfo)
- [x] [node.reload](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#nodesreload_secure_settings) - Need to document this (only available in OpenDistro doc)
- [x] [nodes.stats](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#nodesreload_secure_settings) https://github.com/opensearch-project/documentation-website/pull/1369
- [x] [nodes.usage](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#nodesusage) - Need to document this (only available in OpenDistro doc)
- [x] [put.script](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#nodesusage)
- [x] [rank.eval](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#rank_eval)
- [x] [snapshot.cleanup](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#snapshotcleanup_repository)
- [x] [snapshot.clone](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#snapshotclone)
- [x] [snapshot.create](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#snapshotcreate) | PR #873 
- [x] [snapshot.create_repository](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#snapshotcreate_repository)
- [x] [snapshot.delete](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#snapshotdelete)
- [x] [snapshot.delete_repository](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#snapshotdelete_repository)
- [x] [snapshot.get](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#snapshotget)
- [x] [snapshot.get_repository](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#snapshotget_repository)
- [x] [snapshot.restore](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#snapshotrestore)
- [x] [snapshot.status](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#snapshotstatus)
- [x] [snapshot.verify_repository](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#snapshotverify_repository)
- [x] `GET _scripts/<script-id>` | #1016 
- [x]  `PUT _scripts/<script-id>` | #1016 
- [x]  `PUT _scripts/<script-id>/<context>` | #1016 
- [x]  `DELETE _scripts/<script-id>` | #1016 
- [x] `GET _script_context` | #1016 
- [x] `GET _script_language` | #1016 
- [x] `POST /_scripts/painless/_execute` | #1016 
- [x] `POST /<target>/_reload_search_analyzers` | Not in code base
- [x] `GET /<target>/_reload_search_analyzers` | Not in code base
- [x] `GET /_analyze` https://github.com/opensearch-project/documentation-website/pull/1373/files
- [x] `POST /_analyze` https://github.com/opensearch-project/documentation-website/pull/1373/files
- [x] `GET /<index>/_analyze`https://github.com/opensearch-project/documentation-website/pull/1339
- [x] `POST /<index>/_analyze` https://github.com/opensearch-project/documentation-website/pull/1339
- [x] `POST /<target>/_cache/clear` https://github.com/opensearch-project/documentation-website/pull/1168
- [x] `POST /_cache/clear` https://github.com/opensearch-project/documentation-website/pull/1168
- [x] `DELETE /_dangling/<index-uuid>` https://github.com/opensearch-project/documentation-website/pull/1370
- [x] `POST /_dangling/<index-uuid>` https://github.com/opensearch-project/documentation-website/pull/1370
- [x] [ism_rollup](https://forum.opensearch.org/t/rollup-action-in-ism/5482) https://github.com/opensearch-project/documentation-website/pull/1371

After the request and responses have been documented, please check off the API from this list.

## Test API 

1. Install OpenSearch. We recommend using [Docker](https://opensearch.org/docs/latest/opensearch/install/docker/) with the a sample Docker compose file that [disables the security plugin](https://opensearch.org/docs/latest/opensearch/install/docker/#sample-docker-compose-file-for-development).
2. After installation, run OpenSearch and log into Dashboards.
3. Find the API test console. There, enter each API endpoint listed above with the correct request body. Upon successful execution, the response appears on the right column.

## Time to complete

Each API endpoint should only take about 4 - 5 hours to test, document, and address any review feedback required. With 19 found undocumented endpoints, this assumes an average time to complete of **12 - 15 days**.

**Comment by Naarcha-AWS** [comment]
Looking at this issue and thinking, "That endpoint is already documented!" or "What about this endpoint?". Leave a comment and we'll add or remove endpoints to the list.

**Comment by bgdnlp** [comment]
As per #176, I think ingest pipelines are an undervalued feature that seems to be little known. Would it be possible to add some clear and straight forward documentation about it?

I'm talking about ingest [pipelines](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/ingest.html) and [APIs](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/ingest-apis.html).

I wasn't able to find any dedicated pages for that. There are some references, for example in the _reindex section, but there's no chapter that I could find that explains ingest pipeline or nodes, their role, and how it can replace Logstash for example. Which seems very useful to me, but I'm definitely no expert.

**Comment by lukas-vlcek** [comment]
@bgdnlp I think there is basic documentation about [Ingest APIs](https://opensearch.org/docs/latest/opensearch/rest-api/ingest-apis/index/) but I agree it is missing more detailed information including list of available ingest processors and their doc.

**Comment by bgdnlp** [comment]
To add more details, in case it helps, what I'd like to see as a newcomer is
- A page describing ingestion pipelines and how they can be an alternative to Logstash (I believe). Something like ElasticSearch [docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest.html). Maybe even some kind of howto like [the AWS blog post](https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest.html) where I first found out about this feature.
- A mention and links to the above in the docs, wherever ingestion methods are presented, like [here](https://opensearch.org/docs/latest/clients/agents-and-ingestion-tools/index/).
- A comparison with Logstash. I know that Logstash is more feature rich and moving processing to nodes obviously can have consequences, but for simpler use cases not having to manage Logstash seems like a net win to me, so I'm not sure why it's not presented as an alternative. For example, the [AWS page on data ingestion](https://aws.amazon.com/opensearch-service/the-elk-stack/data-ingestion/) doesn't even mention it, neither does the FAQ. Which makes me think that maybe it's never a good choice.

What I mean is that if I didn't already know about it, if I looked at the documentation around OpenSearch as a newcomer I don't think I'd find it. ElasticSearch, yes, probably. But in OpenSearch it seems to be completely ignored for some reason. I hope it helps.

**Comment by oridool** [comment]
what about the missing snapshot endpoints ?
Specifically, can we use URL parameters in GET endpoint such as `sort` and `from_sort_value` mentioned here? https://www.elastic.co/guide/en/elasticsearch/reference/current/get-snapshot-api.html

**Comment by Naarcha-AWS** [comment]
@steve-O-murphy: Thanks for coming on board, Steve. Here is the list Rest APIs we'll get started:

- [snapshot.create](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#snapshotcreate)
- [snapshot.create_repository](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#snapshotcreate_repository)
- [snapshot.delete](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#snapshotdelete)
- [snapshot.delete_repository](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#snapshotdelete_repository)
- [snapshot.get](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#snapshotget)
- [snapshot.get_repository](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/rest-api-reference/#snapshotget_repository)

**Comment by cwillum** [comment]
API to enable audit logs is in process. [#746](https://github.com/opensearch-project/documentation-website/issues/746).
* GET _plugins/_security/api/audit
* PUT _plugins/_security/api/audit/config
* PATCH _plugins/_security/api/audit
