### ISSUE TITLE
[DOC META] Missing documentation on Mappings 

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#4300]
**What do you want to do?**
 
x Request a change to existing documentation

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
We are missing some information in our content: https://opensearch.org/docs/latest/field-types/index/

Mappings
 - [ ] Runtime fields **N/A to OpenSearch.**
 - [x] Metadata fields: _doc_count, _field_names, _ignored, _id, _index, _meta, _routing, _source, _tier, _type https://github.com/opensearch-project/documentation-website/pull/6933 
 - [x] Mapping parameters: analyzer, boost, coerce, copy_to, doc_values, dynamic, eager_global_ordinals, enabled, format, ignore_above, ignore_malformed, index, index_options, index_phrases, index_prefixes, meta, fields, normalizer, norms, null_value, position_increment_gap, properties, search_analyzer, similarity, store, term_vector https://github.com/opensearch-project/documentation-website/pull/6933 (each parameter has its respective documentation)
 - [x] Mapping limit settings https://github.com/opensearch-project/documentation-website/pull/6933
  - [ ] Removal of mapping types **N/A to OpenSearch. This is in Elasticsearch, not OpenSearch.** 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by hdhalter** [comment]
Community feedback on mappings: 
20230509  | /docs/2.7/field-types/mappings/ | delete a mapping is not provided

**Comment by vagimeli** [comment]
Dev point of contact = @mgodwan; see PR for real-time status updates
