### ISSUE TITLE
[DOC] META - Future Vision for Dashboards

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/documentation-website#4385]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Dashboards design refresh impacts existing documentation, especially tutorials, visual aids, and other UI-related copy. Content audit and revamp needed as this redesign is released. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
POC: @kgcreative 
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4298

**Comment by hdhalter** [comment]
@vagimeli - Can we close this issue in favor of more specific dashboard-change issues?  Thanks!

**Comment by kgcreative** [comment]
Agreed -- i think the future vision doc is too broad and too conceptual for it to lead to a meaningful documentation issue.
