### ISSUE TITLE
[META DOC] Ingest Processors Content Gaps

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/documentation-website#4647]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Close Ingest API content gaps as follows:

**Ingest pipelines**
- [X] Create, get, delete, test pipeline #4299 and #4285  
- [x] Example tutorial
- [x] Accessing data in pipelines
- [ ] Conditional execution in pipelines (nested field conditionals, complex conditionals, conditionals with pipeline processor, conditionals with regular expressions) (see #7348) 
- [x] Enrich data (set up enrich processor, add tutorials (example geolocation, example exact values, example value to a range), enrich policy definition) **Not a processor in OpenSearch**
- [X] Handling pipeline failures https://github.com/opensearch-project/documentation-website/pull/4299/files

**Ingest processors**
- [X] index.md #4299 
- [X] append (10) #4299  
- [X] bytes (20) #4299 
- [X] convert (30) #4299 
- [X] csv (40) #4299 
- [X] date (50) #4299
- [x] date_index_name (60) #5398 
- [x] dissect (70) https://github.com/opensearch-project/documentation-website/pull/5510
- [x] dot_extender (80) https://github.com/opensearch-project/documentation-website/pull/5631
- [x] drop (90) https://github.com/opensearch-project/documentation-website/pull/5767
- [x] enrich (CONFIRMED THIS IS NOT IN OPENSEARCH - Is this in the code? It's an XPACK feature. Doesn't appear in my list of processors when I run `GET /_nodes/ingest?filter_path=nodes.*.ingest.processors`. See also comments in the forum https://forum.opensearch.org/t/ingest-pipelines-support/7716/3.) 
- [x] fail (100) https://github.com/opensearch-project/documentation-website/pull/5980
- [x] foreach (110) https://github.com/opensearch-project/documentation-website/pull/5981
- [x] grok (120) #5019 
- [x] gsub (130) https://github.com/opensearch-project/documentation-website/pull/5983
- [x] html_strip (140) https://github.com/opensearch-project/documentation-website/pull/5984
- [x] IP2Geo (150) https://github.com/opensearch-project/documentation-website/pull/4095
- [x] join (160) https://github.com/opensearch-project/documentation-website/pull/5985/files
- [ ] json (170) https://github.com/opensearch-project/documentation-website/pull/5982
- [x] kv (180) https://github.com/opensearch-project/documentation-website/pull/5781
- [X] lowercase (190) 
- [x] pipeline (200) https://github.com/opensearch-project/documentation-website/pull/5986
- [x] rename (210) https://github.com/opensearch-project/documentation-website/pull/5987
- [x] remove (220)
- [x] script (230) https://github.com/opensearch-project/documentation-website/pull/5988
- [x] set (240) https://github.com/opensearch-project/documentation-website/pull/5989
- [x] sort (250) https://github.com/opensearch-project/documentation-website/pull/5990
- [x] sparse_encoder (260)
- [x] split (270) https://github.com/opensearch-project/documentation-website/pull/5991
- [x] text_embedding (280)
- [x] text_image (290)
- [x] trim (300) https://github.com/opensearch-project/documentation-website/pull/5993
- [x] uppercase (310)
- [x] urldecode (320) https://github.com/opensearch-project/documentation-website/pull/5994
- [x] user_agent (330) https://github.com/opensearch-project/documentation-website/pull/5995

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by vagimeli** [comment]
@heemin32 The doc team is working through Ingest APIs content gaps. This issue is tracking those gaps. At your availability, will you review and provide your feedback on anything we've missed? Thank you.

**Comment by heemin32** [comment]
Enrich data (set up enrich processor, add tutorials (example geolocation, example exact values, example value to a range), enrich policy definition) is not supported in OpenSearch.

**Comment by hdhalter** [comment]
@vagimeli - Should we keep this open until all ingest processors are documented, or did you open a new issue for tracking?

**Comment by vagimeli** [comment]
@heemin32 Is the `enrich` processor in the code? It's an XPACK feature. Doesn't appear in my list of processors when I run GET /_nodes/ingest?filter_path=nodes.*.ingest.processors. See also comments in the forum https://forum.opensearch.org/t/ingest-pipelines-support/7716/3

**Comment by heemin32** [comment]
> @heemin32 Is the `enrich` processor in the code? It's an XPACK feature. Doesn't appear in my list of processors when I run `GET /_nodes/ingest?filter_path=nodes.*.ingest.processors`. See also comments in the forum https://forum.opensearch.org/t/ingest-pipelines-support/7716/3

OpenSearch does not have enrich processor

**Comment by vagimeli** [comment]
@vamshin This is the primary PR for tracking the ingest processor content gaps. As I write the docs, I'll track each processor's PR in this primary PR. I'll tag you in those PRs so that you have visibility into the needed technical reviews by your team. Thanks for your helping in moving these docs forward.

**Comment by hdhalter** [comment]
Hi @vagimeli , we will need documentation for the kv processor for a 2.12 feature. Can you please prioritize on that one next? Thanks! See https://github.com/opensearch-project/documentation-website/issues/5651

**Comment by hdhalter** [comment]
@vagimeli - did you mean to close this? We should keep it open until all are complete.

**Comment by dblock** [comment]
[Triage -- attendees [1](https://github.com/dblock), [2](https://github.com/peternied), [3](https://github.com/reta), [4](https://github.com/krisfreedain), [5](https://github.com/Getsaurabh02), [6](https://github.com/gkamat), [7](https://github.com/scrawfor99)]
