### ISSUE TITLE
[DOC] [Remote State] Meta issue for documentation

### ISSUE THREAD

**Issue by rahulkarajgikar** [opensearch-project/documentation-website#5357]
**What do you want to do?**
 
- [X] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

## Description

We need to update public documentation for any PRs raised for remote cluster state 

PRs tracked:

https://github.com/opensearch-project/OpenSearch/pull/10814
https://github.com/opensearch-project/OpenSearch/pull/10665
https://github.com/opensearch-project/OpenSearch/pull/10447

**Comment by hdhalter** [comment]
@rahulkarajgikar - And which features are targeting 2.12?

**Comment by hdhalter** [comment]
Hi @Naarcha-AWS , can you please track this down and see if there is anything related to 2.12? Or are these already implemented/documented in a previous version?

**Comment by soosinha** [comment]
@hdhalter These are being tracked for 2.12 release

**Comment by hdhalter** [comment]
Thanks, @soosinha ! Can you please add these issues to the roadmap/project tracker for visibility?

**Comment by soosinha** [comment]
@hdhalter These issues are already resolved and code is merged in 2.x branch.
Do you still want me to add in the project tracker? If yes, then can you provide the project tracker link ?

**Comment by hdhalter** [comment]
> @hdhalter These issues are already resolved and code is merged in 2.x branch. Do you still want me to add in the project tracker? If yes, then can you provide the project tracker link ?

Yes, so we can see all features at a glance. The marketing team uses this list to determine what features to highlight in the release blog.
