### ISSUE TITLE
[DOC] META: Flint 

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/documentation-website#5375]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [X] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
 Track documentation writing assignments and tasks. 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.
#3454 #4577

**Comment by hdhalter** [comment]
@vagimeli @derek-ho - do we have any flint-related features going out in 2.12? If so, can we create individual issues for specific features and close this one? Thanks.
