### ISSUE TITLE
[DOC-META] Installation guide refactor + recommended config (Tarball, Docker, Yum, RPM)

### ISSUE THREAD

**Issue by JeffH-AWS** [opensearch-project/documentation-website#789]
## What do you want to do?

Current documentation does not clearly provide all of the steps required for standing up OpenSearch and OpenSearch Dashboards, whether the installation is performed using Docker or manually by inflating and configuring the tarball archive.

This will also require moving things within the docs so they make more sense in their given context.  Sub-tasks will be defined as work progresses.

## Milestone 1 Tasks - OpenSearch Core
- [X] Review tar archive install steps
- [X] Stand up OpenSearch node on a host from tar.gz
- [x] Submit PR with enhancements to tar archive install (Merged)
- [x] Review Docker install steps
- [x] Stand up OpenSearch node on a host using Docker
- [x] Submit PR with enhancements to Docker install (Merged)
- [x] Review RPM/Yum install steps
- [x] Stand up OpenSearch node on a host using RPM/Yum
- [x] Submit PR with enhancements to RPM/Yum install (Merged)
- [x] Review existing materials and create a quick start guide (in review)

## Milestone 2 Tasks - OpenSearch Dashboards
-- Removing the tasks here since Dashboards content is handled by another writer now --

Linked PRs:

Removing this section - PRs that are relevant are tagged with "Related to #789"

**Comment by JeffH-AWS** [comment]
Making great progress on the tarball installation method.  I'm currently formatting the steps in markdown and should have a PR up soon.  Steps are all validated by technical resources.  I'm also looking to include a brief blurb in the overview to describe basic assumed competencies (like familiarity with Linux CLI, etc.)

**Comment by JeffH-AWS** [comment]
As I'm peeling back the many layers to this onion I continue to uncover additional things that need to be fixed up.  For example, we have documentation in the Tarball installation guide about installing the Performance Analyzer plugin.  It looks like this may have been included here because a manual configuration is required for `tarball` installations of OpenSearch.  This is going to take a little bit of research.  I'm going to keep working on it this afternoon but will have to shift gears to a 2.2 deliverable next Monday.  The scope for that hasn't been defined yet (I'm meeting with the developer in the afternoon on Monday) so I'm not sure how many hours of effort that will take.

**Comment by JeffH-AWS** [comment]
During a sync today with Nate A. and Himanshu S. there we some good call-outs.  I made some changes and pushed them to the draft PR based on feedback.

Himanshu pointed out that the landing page for the security plugin configuration (https://opensearch.org/docs/latest/security-plugin/configuration/index/) doesn't make it clear which files are being modified.  However, I did find the steps listed in https://opensearch.org/docs/latest/security-plugin/configuration/yaml/ so I explicitly linked to that page. In the future I think we might want to break it out into its own page, but that would make sense as a natural step as our docs evolve and begin to incorporate more available YAML settings.

**Comment by JeffH-AWS** [comment]
Tarball installation guide is pending editorial review. Will merge once that is complete.

**Comment by JeffH-AWS** [comment]
Beginning work on Docker refactor.

**Comment by JeffH-AWS** [comment]
Tarball refactor is completed and published.  RPM/Yum next because of the significant overlap and reduced editorial review burden.  Docker will come after that since it will be the ugly duckling of the bunch, with less parity to other guides and additional assumed skillsets.

**Comment by JeffH-AWS** [comment]
RPM/Yum installation keep getting pushed back due to other priorities...will try to continue work this week but it looks like I'll be getting back on it next week.

**Comment by JeffH-AWS** [comment]
Finally got some time to circle back around to this. Finishing up the steps for RPM/Yum install.

**Comment by JeffH-AWS** [comment]
Next topic to cover: Docker install of dashboards

**Comment by JeffH-AWS** [comment]
Switching over to migration documentation now. Parking this ticket until I have cycles to pick it back up and review Helm, Ansible, and K8s.

**Comment by JeffH-AWS** [comment]
Putting this back in progress for the morning while I work on distilling a quickstart guide from the new Docker material.

**Comment by JeffH-AWS** [comment]
Quick start guide is in tech review now. Waiting on feedback regarding the depth of the guide - is more needed? Less? I might get it merged before Thanksgiving if the approvals and reviews are quick but no guarantees.

**Comment by JeffH-AWS** [comment]
Refactor completed for tarball, RPM/YUM, and Docker installations. Additionally, I created a quickstart guide from scratch and pushed it.

Next priority is upgrading OS, followed by migrations from other platforms or infrastructure.
