### ISSUE TITLE
[Doc-Meta] Redesign of Documentation Website

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/documentation-website#809]
The [OpenSearch.org](https://opensearch.org/docs/latest) documentation website does not raise the bar when compared to other open-source documentation websites. As we continue to grow our documentation library, we need to make sure it is built to scale, and also provides a delightful experience. 

Improvement ideas: 
- [ ] Update the summary information
- [ ] Update the rest of the content on the doc home page to quickly direct users to the information they need most, for example: Log Analytics, Site Search, Observability, Getting Started, What's New, Latest Release Notes, etc.
- [ ] Restructure the TOC to make it easier for users to find content
- [ ] Redesign the home page into a more modern look and feel (e.g., use different Jekyll template or React) 
- [ ] Include a feedback mechanism (sentiment measurement, aka, thumbs up/down, comments)

Feel free to comment. More details to follow.
