### ISSUE TITLE
[DOC] Broken links to opensearch.org in plugin READMEs

### ISSUE THREAD

**Issue by AWSHurneyt** [opensearch-project/documentation-website#921]
**What do you want to do?**
 
- [ ] Request a change to existing documentation
- [ ] Add new documentation
- [x] Report a technical problem with the documentation
- [ ] Other 

**Tell us about your request.** Provide a summary of the request and all versions that are affected.
Several of the plugins (e.g., [anomaly detection](https://github.com/opensearch-project/anomaly-detection/blob/main/README.md?plain=1#L4), [alerting](https://github.com/opensearch-project/alerting/blob/main/README.md?plain=1#L4), [ISM](https://github.com/opensearch-project/index-management/blob/main/README.md?plain=1#L5), etc.) contain links to the opendistro website in the READMEs for their back and frontend repositories. These links redirect to [opensearch.org](opensearch.org), but not to a functioning forum page. The link in the Alerting README for example links to https://forum.opensearch.org/c/alerting/, which displays a `Oops! That page doesn’t exist or is private` error message.

Is it possible for the ODFE pages to redirect to more appropriate forum pages on the OpenSearch site, or would the plugins need to update their READMEs with new links?

This is a list of PRs for individual plugin repositories affected by this issue:
- [x] Alerting plugin [#545](https://github.com/opensearch-project/alerting/pull/545)
- [x] Anomaly Detection plugin [#659](https://github.com/opensearch-project/anomaly-detection/pull/659)
- [x] Asynchronous search plugin [#178](https://github.com/opensearch-project/asynchronous-search/pull/178)
- [ ] Cross-cluster replication plugin [#548](https://github.com/opensearch-project/cross-cluster-replication/pull/548)
- [ ] Dashboards reports plugin [#455](https://github.com/opensearch-project/dashboards-reports/pull/455)
- [x] Index Management plugin [#499](https://github.com/opensearch-project/index-management/pull/499)
- [x] k-NN plugin [#540](https://github.com/opensearch-project/k-NN/pull/540)
- [x] ML Commons plugin [#418](https://github.com/opensearch-project/ml-commons/pull/418)
- [ ] Observability plugin [#999](https://github.com/opensearch-project/observability/pull/999)
- [x] Performance Analyzer plugin [#266](https://github.com/opensearch-project/performance-analyzer/pull/266)
- [x] SQL plugin [#809](https://github.com/opensearch-project/sql/pull/809)

**Comment by cwillum** [comment]
@Naarcha-AWS Do you know if there's a workaround to avoid having to fork each one of these repositories and creating a new branch for each?

**Comment by cwillum** [comment]
Waiting for owners/contributors of the various repositories to finish reviewing and merging the PRs. Once all of the PRs listed above have been merged, I'll close this issue.

**Comment by cwillum** [comment]
Commented in remaining un-merged PRs (checkmark in list above indicates PR has been merged). Asked for final review and merge on my behalf (I don't have permission in those repos).

**Comment by AWSHurneyt** [comment]
I just wanted to quickly clarify that these broken links are also present in the README files of the frontend plugins (e.g., [alerting dashboards](https://github.com/opensearch-project/alerting-dashboards-plugin/blob/main/README.md)) as well.

**Comment by cwillum** [comment]
@AWSHurneyt That's a good point. I think at this stage, it might be best to follow the advice of @saratvemulapalli and add a new issue in [opensearch-plugins](https://github.com/opensearch-project/opensearch-plugins/issues): "if [an issue] impacts 2 or more plugins, you can open a PR with a suggestion in [STANDARDS.md](https://github.com/opensearch-project/opensearch-plugins/blob/main/STANDARDS.md) and we could campaign it."

**Comment by AWSHurneyt** [comment]
@cwillum Agreed. I've created the above issues in the opensearch-plugins folder.

**Comment by Naarcha-AWS** [comment]
Closing this issue since every broken link in question has either been fixed through merge or has a PR associated with it.
